
# A list of the worlds this is disabled in. eg. disabledWorlds: [world, creative]
disabledWorlds: []

# When true, disabledWorlds becomes a list of worlds to enable in
invert: false

# The distance in blocks signs can be sign from
maxSignRange: 20

# The distance in blocks sign text can be seen from. This cannot be greater or equal to maxSignRange
textRange: 10 

# Per world settings. Example below
worldSettings:
#  world:
#    maxSignRange: 40
#    textRange: 15
     